cache: pip

matrix:
  fast_finish: true
  include:
    - name: "Black"
      env: RUN=black
      language: python
      python: 3.7
      os: linux
      dist: bionic

script: python3 test/test1.py

after_failure:
  - sleep 10;
  - echo == End ==

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "pypi-AgEIcHlwaS5vcmcCJDdhMTkyODMzLWE1Y2MtNDc3My1hYzI0LTM2ZGU5NTRkNmY4MAACPnsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJ0YXB0YXJnZXR2aWV3Il19LCAidmVyc2lvbiI6IDF9AAAGIAnncDRYv5MyAxTGReIb8VblzDX1pWqXr5dDNL5OhBc3"
  distributions: "sdist bdist_wheel"
  on:
    tags: true
